### ISSUE TITLE
Deploying two vaults results in the second deploy failing.

### ISSUE THREAD

**Issue by slundqui** [delvtech/everlong#35]
When running deploy as documented in the README, deploying two strategies and vaults (with a one to one mapping) fails when attempting to deploy the second vault (i.e., `DeployVault.s.sol`).

Order of operations:
1. Launch mainnet fork.
2. Run `DeployRoleManager.s.sol`.
3. Run `DeployEverlongStrategyKeeper.s.sol`.
4. Run `DeployEverlongStrategy.s.sol` twice, with the following parameters:
```
NAME='everlong_strategy_0' HYPERDRIVE='0xd41225855A5c5Ba1C672CcF4d72D1822a5686d30'
NAME='everlong_strategy_1' HYPERDRIVE='0xd41225855A5c5Ba1C672CcF4d72D1822a5686d30'
```
5. Run `DeployVault.s.sol` twice, with the following parameters:
```
STRATEGY_NAME='everlong_strategy_0' NAME='vault_0' SYMBOL='V' CATEGORY=0
STRATEGY_NAME='everlong_strategy_1' NAME='vault_1' SYMBOL='VV' CATEGORY=0
```

The first `DeloyVault.s.sol` runs successfully, the second fails with the following error:
```
script failed: custom error 29ab51bf:00000000000000000000000093a9cc28f57d36cb87127f0cef42cd61ca0456a3
```

Debugging shows the second execution fails on this line:
https://github.com/delvtech/everlong/blob/daabc00952af85b40cce0e83fdd391a0be2fb5d6/script/DeployVault.s.sol#L181

**Comment by mcclurejt** [comment]
Have you tried changing the vault's category?

Yearn requires that no two vaults can have the same asset and category, since the asset is the same for each, the category has to be updated.

Since the default is 0, trying the following should work:

```sh
STRATEGY_NAME='everlong_strategy_1' NAME='vault_1' SYMBOL='VV' CATEGORY=1
```

**Comment by slundqui** [comment]
This seemed to have fixed it, thanks!
